### ISSUE TITLE
feature request: ability to ignore <a href="#">hash char url</a>

### ISSUE THREAD

**Issue by rkoberg** [DavidAnson/grunt-check-pages#3]
URLs with a hash character will always be valid and can safely be ignored, at least as an option. Someone might want to check if these occur, and if so they would be an error.

I modified checkPages like so:

function addLinks($, element, attribute, page, index) {
    var pageHostname = url.parse(page).hostname;
    $(element).each(function() {
      var link = $(this).attr(attribute);
      if (link && link !== '#') {
        var resolvedLink = url.resolve(page, link);
        var parsedLink = url.parse(resolvedLink);
        if (((parsedLink.protocol === 'http:') || (parsedLink.protocol === 'https:')) &&
            (!options.onlySameDomain || (parsedLink.hostname === pageHostname)) &&
            !isLinkIgnored(resolvedLink)) {
          // Add to beginning of queue (in order) so links gets processed before the next page
          pendingCallbacks.splice(index, 0, testLink(page, resolvedLink));
          index++;
        }
      }
    });
    return index;
  }

**Comment by DavidAnson** [comment]
Thanks for the suggestion! I'll get to this soon.

**Comment by DavidAnson** [comment]
I started looking at this and think I have a nice approach for minimizing unnecessary requests due to '#'. I should be able to publish an update soon.

Regarding your idea to add an option to error for '#', I've thought about it a bit and didn't come up with a compelling reason to block the use of '#'. Did you have something in mind?

**Comment by rkoberg** [comment]
What I had in mind for the error condition was that it is sometimes an error to forget to replace the '#' with a real URL or path. It might have been left over from a design/mock-up phase.

**Comment by DavidAnson** [comment]
My approach for the original feature request is to only visit each link once - if the same link is seen again, it is skipped. In the case of '#', because the fragment identifier is client-only it is removed from the link when determining if that link has been seen before. However, it's necessary to visit a '#' link at least once so link-related checks get a chance to run (ex: redirection and local link detection). Instead of adding an option, this will become the default behavior; it seems desirable and without a downside.

Please let me know if this seems reasonable.

PS - You make a good point about a rule to block '#', and I'll follow up with that separately. (Incidentally, this is another link-related check that can't be skipped by ignoring '#' links entirely.)

**Comment by DavidAnson** [comment]
Per the discussion above, I believe the new v0.8.0 release addresses both feature requests. I hope you like it! :)
